server {
  bind_address = "0.0.0.0"
  bind_port = "8081"
  trust_domain = "zgitea.local"
  data_dir = "/run/spire/server"
  log_level = "INFO"
}
plugins {
  DataStore "memory" {}
  NodeAttestor "join_token" {
    plugin_data { }
  }
  KeyManager "memory" {}
}
